name: Deploy (Pulumi)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::564818402695:role/CICD-GitHubActions
          aws-region: us-east-1

      - name: Pulumi Login
        uses: pulumi/actions@v5
        with:
          command: login

      - name: Select Pulumi stack
        run: pulumi stack select dev

      - name: Pulumi Up (Deploy)
        uses: pulumi/actions@v5
        with:
          command: up
          args: --yes