name: Deploy (Pulumi)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::564818402695:role/github-pipeline-role
          aws-region: us-east-1

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}